// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3620.Robot;

/**
 *
 */
public class  AutonomousTurn extends Command {

	public double angle;
    public AutonomousTurn(double degrees) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	angle = degrees;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public AutonomousTurn(){
    	this(45);
    }
 
    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.drive.gyroReset();
    	System.out.println("autoTurn Start");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (angle < 0)
    	{
    	Robot.drive.setDrive(0, .75);
    	}
    	else
    	{
    		Robot.drive.setDrive(0, -.75);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (Math.abs(Robot.drive.getGyroAngle()) >= Math.abs(angle))
        {
        	return true;
        }
        else{
        	return false;
        }
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.turnMotorsOff();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
