// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3620.Robot;

/**
 *
 */
public class  liftManual extends Command {

    public liftManual() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.liftPID);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.liftPID.disable();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double speed = Robot.oi.operatorJoystick.getRawAxis(5);
    	if (Robot.liftPID.limitTop() == false && Robot.liftPID.limitBottom() == false)
    	{
    		System.out.println("1");
    		Robot.liftPID.setMotor(speed);
    	}
    	else if (Robot.liftPID.limitBottom() && speed < 0)
    	{
    		System.out.println("2");
    		Robot.liftPID.setMotor(speed);
    	}
    	else if (Robot.liftPID.limitTop() && speed > 0)
    	{
    		System.out.println("3");
    		Robot.liftPID.setMotor(speed);
    	}
    	else
    	{
    		System.out.println("Cannot move! Against limit switch!");
    	}
    	System.out.println("Limit Top: " + Robot.liftPID.limitTop());
    	System.out.println("Limit Bottom: " + Robot.liftPID.limitBottom());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println("lift manual end");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
